
volumes:
  modelos_nlp:
    external: true
    name: modelos_nlp

services:
  redis:
    container_name: redisCache
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery_worker:
    container_name: celery_worker
    build:
      context: ./celeryBackend
      dockerfile: celery.Dockerfile
    volumes:
      - modelos_nlp:/app/data
    env_file:
      - .env.prod
    command: celery -A task.celery_app worker --loglevel=info --concurrency=3 --pool=prefork
    depends_on:
      - redis
  
  celery_beat:
    container_name: celery_beat
    build:
      context: ./celeryBackend
      dockerfile: celery.Dockerfile
    env_file:
      - .env.prod
    volumes:
      - modelos_nlp:/app/data
    
    command: celery -A task.celery_app beat --loglevel=info

    depends_on:
      - redis
      - celery_worker 
    
  celery_flower:
    container_name: celery_flower
    build:
      context: ./celeryBackend
      dockerfile: celery.Dockerfile
    env_file:
      - .env.prod
    ports:
      - "5555:5555"

    volumes:
      - modelos_nlp:/app/data

    command: celery -A task.celery_app flower --port=5555

    depends_on:
      - redis
      - celery_worker
      - celery_beat

