services:
  redis:
    container_name: redisCache
    image: redis:7-alpine
    ports:
      - "6379:6379"

  fastapi:
      container_name: OglocBackend
      image: bitzkort/trabajo_de_grado_ogloc:fastapi
      command: bash -c "python -m uvicorn main:app --host 0.0.0.0 --port 8000"
      ports:
        - "8000:8000"

      env_file:
        - .env.dev
      depends_on:
        - redis

  celery_worker:
      container_name: celery_worker
      image: bitzkort/trabajo_de_grado_ogloc:celery
      env_file:
        - .env.dev
      command: celery -A task.celery_app worker --loglevel=info --concurrency=2 --prefetch-multiplier=1 --pool=prefork
      depends_on:
        - redis
    
  celery_beat:
    container_name: celery_beat
    image: bitzkort/trabajo_de_grado_ogloc:celery
    env_file:
      - .env.dev
    command: celery -A task.celery_app beat --loglevel=info

    depends_on:
      - redis
      - celery_worker 
    
  celery_flower:
    container_name: celery_flower
    image: bitzkort/trabajo_de_grado_ogloc:celery
    env_file:
      - .env.dev
    ports:
      - "5555:5555"

    command: celery -A task.celery_app flower --port=5555

    depends_on:
      - redis
      - celery_worker
      - celery_beat