
volumes:
  modelos_nlp:
    external: true
    name: modelos_nlp

services:
  redis:
    container_name: redisCache
    image: redis:7-alpine
    ports:
      - "6379:6379"

  fastapi:
    container_name: fastAPI-Server
    build:
      context: ./fastAPI
      dockerfile: Dockerfile
    command: bash -c "python -m uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - modelos_nlp:/app/data
    env_file:
      - .env.prod
    depends_on:
      - redis

